# Generated by Django 6.0 on 2025-12-09 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_leaverequest_days_triprequest_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripReportRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip_report_recipient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('rejected', '반려')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_approvals', to=settings.AUTH_USER_MODEL)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='attendance.leaverequest')),
            ],
            options={
                'ordering': ['leave', 'order'],
                'unique_together': {('leave', 'order')},
            },
        ),
    ]
